version: 2.1

### It's a good practice to keep your commands at the top of the config file. In this project, you'll need at least 2 commands:

# commands:
#   destroy-environment:
#     description: Destroy backend and frontend cloudformation stacks given a workflow ID.
#     ...

#   revert-migration:
#     description: Revert the last migration if successfully run in the current workflow.
#     ...

jobs:

#  build-frontend:
  buildFrontEnd:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - run:
            name: BUILD frontend
            command: |
              cd frontend
              npm i
              npm run build
#  build-backend:
  buildBackEnd:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - run:
            name: BUILD backend 
            command: |
              cd backend
              npm i
              npm run build      
#  test-frontend:
  testFrontEnd:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout     
      - run:
          name: TEST frontend
          command: |
            cd frontend
            npm i
            npm run test
      - store_test_results:
          path: test-results
#  test-backend:
  testBackEnd:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: TEST backend
          command: |
            cd backend
            npm i
            npm run test   
      - store_test_results:
          path: test-results   

#  est-backend:

#  can-frontend:

#  scan-backend:

#  deploy-infrastructure:

#  configure-infrastructure:

#  run-migrations:

#  deploy-frontend:

#  deploy-backend:  

#  smoke-test:

#  cloudfront-update:

workflows:
  default:
    jobs:
      - buildBackEnd
      - buildFrontEnd
      - testFrontEnd:
          requires:
            - buildFrontEnd
      - testBackEnd:
          requires:
            - buildBackEnd

